export const fontLists = [
    'Arial', 'Verdana', 'Helvetica', 'Tahoma', 'Trebuchet MS',
    'Times New Roman', 'Georgia', 'Garamond',
    'Courier New', 'Lucida Console',
    'Segoe UI', 'Roboto', 'San Francisco', 'Ubuntu'
]

export const fixdata = {
    "ScriptID": "202502071223160",
    "id": 636,
    "bulletinname": "simnews1",
    "bulletinlock": 0,
    "bulletindate": "2025-02-06T18:30:00.000Z",
    "bulletintype": "",
    "rowid": "202502071223160",
    "slno": 1,
    "SlugName": "No Slug Name",
    "Script": "No Script",
    "scriptmodifiedtime": "2025-02-07T06:55:51.000Z",
    "createdtime": "2025-02-07T06:53:16.000Z",
    "createdby": "binoy",
    "currentuser": "rajeev",
    "LastModifiedTime": "2025-02-07T11:46:46.000Z",
    "lastmodifiedby": null,
    "Lockscript": 0,
    "lockedby": null,
    "WordsCount": 1.31,
    "EditCode": "0",
    "autosavestatus": 0,
    "OneLinerText": null,
    "onelinermodifiedtime": null,
    "importedscriptid": null,
    "importedbulletinname": null,
    "media1": null,
    "media2": null,
    "media3": null,
    "media4": null,
    "media5": null,
    "media1duration": "00:00:00",
    "media2duration": "00:00:00",
    "media3duration": "00:00:00",
    "media4duration": "00:00:00",
    "media5duration": "00:00:00",
    "mediamodifiedtime": null,
    "mediamodifiedby": null,
    "source": null,
    "dropstory": 0,
    "archivestatus": 0,
    "graphicsid": null,
    "reporter1": null,
    "reporter2": null,
    "location": null,
    "repeated": 0,
    "approved": 1,
    "deleted": 0,
    "voiceover": 0,
    "RunOrder": 1,
    "CreatedTime": "2025-02-07T06:53:16.000Z",
    "ScriptLastModifiedTime": "2025-02-07T06:55:51.000Z",
    "Approval": 1,
    "MediaInsert": null,
    "DropStory": 0
};

export const languages = [
    "en-US",
    "hi-IN",
    "te-IN",
    "ta-IN",
    "mr-IN",
    "gu-IN",
    "kn-IN",
    "ml-IN",
    "pa-Guru-IN",
    "ur-IN",
    "ar-SA",
    "bn-BD",
    "bn-IN",
    "cs-CZ",
    "da-DK",
    "de-AT",
    "de-CH",
    "de-DE",
    "el-GR",
    "en-AU",
    "en-CA",
    "en-GB",
    "en-IE",
    "en-IN",
    "en-NZ",
    "en-US",
    "en-ZA",
    "es-AR",
    "es-CL",
    "es-CO",
    "es-ES",
    "es-MX",
    "es-US",
    "fi-FI",
    "fr-BE",
    "fr-CA",
    "fr-CH",
    "fr-FR",
    "he-IL",
    "hi-IN",
    "hu-HU",
    "id-ID",
    "it-CH",
    "it-IT",
    "jp-JP",
    "ko-KR",
    "nl-BE",
    "nl-NL",
    "no-NO",
    "pl-PL",
    "pt-BR",
    "pt-PT",
    "ro-RO",
    "ru-RU",
    "sk-SK",
    "sv-SE",
    "ta-IN",
    "ta-LK",
    "th-TH",
    "tr-TR",
    "ur_PK",
    "zh-CN",
    "zh-HK",
    "zh-TW",
    "bh-IN"
];