// import './globals.css'
import ProviderWrapper from './store/ProviderWrapper';

const pad = (value) => String(value).padStart(2, '0');

const createTimestampedTitle = () => {
  const now = new Date();
  const day = pad(now.getDate());
  const month = pad(now.getMonth() + 1);
  const year = now.getFullYear();
  const hours = pad(now.getHours());
  const minutes = pad(now.getMinutes());
  const seconds = pad(now.getSeconds());

  return `Teleprompter_${day}${month}${year}_${hours}${minutes}_${seconds}`;
};

export const metadata = {
  title: createTimestampedTitle(),
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ProviderWrapper>
          {children}
        </ProviderWrapper>
      </body>
    </html>
  );
}
