import './globals.css'
import ProviderWrapper from './store/ProviderWrapper';
import { Analytics } from "@vercel/analytics/react"
export const metadata = {
  title: "Teleprompter_280425_1",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ProviderWrapper>
          {children}
        </ProviderWrapper>
      </body>
    </html>
  );
}
